### Site info:
title: Musicap3
tagline: An√°lisis de productos y accesorios MP3
author: Sergio de Diego
description: "Analisis de productos y accesorios MP3." # You can edit this line in _config.yml. It will appear in your document head meta and in your feed.xml site description
keywords: "Mp3"

locales:
    en:
     
      Archives: "Archives"
      Blogroll: "Blogroll"
      Categories: "Categories"
      Copyright_Notice: "Copyright Notice"
      Resent_Posts: "Resent Posts"
      Tags: "Tags"
      Previous: "Older"
      Next: "Newer"
      PostedInCategories: "Posted in"
      Taggedwith: "and tagged"  
      PostDate: "on "





default_column: "two" # blog style: two columns, if default_column != "two", you will see a one column blog.
default_locale: "en" # blog sidebar language set, only include: English(en) and Chinese (cn)



### your Blogroll info, only name can shown on the page.

Blogroll:
    - name: musicap3
      href: http://musicap3.com
      title: Analisis de productos y accesorios MP3

 # Scripts
google_analytics: "UA-3866214-1" # tracking id, e.g. "UA-000000-01"
disqus_shortname:


### Build settings
markdown: kramdown
highlighter: pygments
permalink: /:title/
paginate: 5
